version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: nokogiri
    versions:
    - 1.11.1
    - 1.11.2
  - dependency-name: rspec-rails
    versions:
    - 4.0.2
    - 4.1.0
    - 5.0.0
  - dependency-name: activerecord
    versions:
    - 6.0.3.5
    - 6.1.3
  - dependency-name: activejob
    versions:
    - 6.0.3.4
    - 6.0.3.5
    - 6.1.3
  - dependency-name: actionpack
    versions:
    - 6.0.3.4
    - 6.0.3.5
    - 6.1.3
  - dependency-name: rails
    versions:
    - 6.0.3.4
    - 6.0.3.5
    - 6.1.3
  - dependency-name: railties
    versions:
    - 6.0.3.4
    - 6.0.3.5
    - 6.1.3
  - dependency-name: actionview
    versions:
    - 6.0.3.4
    - 6.0.3.5
    - 6.1.3
  - dependency-name: activesupport
    versions:
    - 6.0.3.4
    - 6.0.3.5
    - 6.1.3
  - dependency-name: loofah
    versions:
    - 2.9.0
  - dependency-name: ffi
    versions:
    - 1.14.2
